# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomSuggestionRowSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomSuggestionRowSample
  pod 'SuggestionRow', :git => 'https://github.com/bsv-hienpham1991/SuggestionRow.git'
  
  target 'CustomSuggestionRowSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
